#!/usr/bin/env bash

#==============USER MODS=======================================
src_dir=/glade/work/afoster/FATES_calibration/CTSM_calib
dir_tag=/glade/work/afoster/FATES_calibration/FATES_SP_OAAT
case=ctsm51FATES_SP_OAAT
chargenum=P93300041
scratch_dir=/glade/derecho/scratch/afoster
archive_dir=/glade/derecho/scratch/afoster/archive
datm_dir=/glade/work/afoster/FATES_calibration/user_datm_files
user_nl_dir=/glade/work/afoster/FATES_calibration/user_nl_files

scenario=SatPhen_derecho
cyear=2000
compset=2000_DATM%GSWP3v1_CLM51%FATES_SICE_SOCN_SROF_SGLC_SWAV

#==============================================================
# case setup and run
#==============================================================

## case name and path
suff=_${scenario}_${cyear}
case_name=${case}${suff}
case_path=${dir_tag}/${case_name}

# change into cime directory
cd ${src_dir}/cime/scripts

## create a new case
./create_newcase --case ${case_path} --compset ${compset} --res f19_g17 --project ${chargenum} --run-unsupported 
cd ${case_path}

## copy user_nl_clm and user_nl_datm_streams into this file
cp ${user_nl_dir}/user_nl_clm .

# env_run.xml
./xmlchange RUN_STARTDATE=0001-01-01
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=10
./xmlchange RESUBMIT=5
./xmlchange MASK_MESH='/glade/work/afoster/FATES_calibration/mesh_files/lnd_mesh.nc'
./xmlchange ATM_DOMAIN_MESH='/glade/work/afoster/FATES_calibration/mesh_files/lnd_mesh.nc'
./xmlchange LND_DOMAIN_MESH='/glade/work/afoster/FATES_calibration/mesh_files/lnd_mesh.nc'
./xmlchange DATM_YR_ALIGN=1
./xmlchange DATM_YR_START=2005
./xmlchange DATM_YR_END=2014

./xmlchange CLM_ACCELERATED_SPINUP=off

# env_mach_pes.xml
./xmlchange NTASKS_OCN=112
./xmlchange NTASKS_WAV=112
./xmlchange NTASKS_GLC=112
./xmlchange NTASKS_ICE=112
./xmlchange NTASKS_ROF=112
./xmlchange ROOTPE_LND=16
./xmlchange ROOTPE_OCN=16
./xmlchange ROOTPE_WAV=16
./xmlchange ROOTPE_GLC=16
./xmlchange ROOTPE_ICE=16
./xmlchange ROOTPE_ROF=16
./xmlchange ROOTPE_ATM=0
./xmlchange ROOTPE_CPL=16
./xmlchange NTASKS_LND=112
./xmlchange NTASKS_ATM=16
./xmlchange NTASKS_CPL=112

# env_workflow.xml
./xmlchange JOB_WALLCLOCK_TIME=02:00:00

# Setup case
./case.setup

# Generate namelists
./preview_namelists

# Build case
qcmd -- ./case.build
